### ISSUE TITLE
server/asset/btc: nil pointer deref error encountered in test

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1188]
Transient error encountered when testing for unrelated PR #1187.

```
--- FAIL: TestReorg (1.16s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x98f0b9]

goroutine 57 [running]:
testing.tRunner.func1.2(0x9e83a0, 0xe56410)
	/usr/local/go/src/testing/testing.go:1143 +0x49f
testing.tRunner.func1(0xc00008b980)
	/usr/local/go/src/testing/testing.go:1146 +0x695
panic(0x9e83a0, 0xe56410)
	/usr/local/go/src/runtime/panic.go:971 +0x499
decred.org/dcrdex/server/asset/btc.TestReorg(0xc00008b980)
	/home/buck/github/decred/dcrdex/server/asset/btc/btc_test.go:1315 +0x8f9
testing.tRunner(0xc00008b980, 0xb9f910)
	/usr/local/go/src/testing/testing.go:1193 +0x203
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x5d8
FAIL	decred.org/dcrdex/server/asset/btc	3.216s

```

**Comment by chappjc** [comment]
`blockPollInterval` of 50ms is pretty darn short so it's not too surprising the `btc.(*Backend).run` goroutine doesn't get CPU time fast enough more frequently in CI
