### ISSUE TITLE
Web: Random panic in unmarket.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1496]
I'm unsure yet on how to reproduce this yet buy have seen it a few times. Seems like a harmless panic, but a panic nonetheless. Here I think I just shut down the server that dexc was connected to.

```
2022-02-28 17:50:44.216 [DBG] CORE[dcr]: tip change: 608 (32ffc0e0750322d9673b5eba2d94f9d4787a6e6fca4df87e81c81d7bf4c2cc7d) => 609 (164617a657d23a8b493d92abc23fc54ca3e57a0b25f8bc843a16ee05d660894c)
2022-02-28 17:50:44.216 [TRC] CORE: processing tip change for dcr
2022-02-28 17:50:44.224 [TRC] CORE: notify: |DATA| (balance) balance updated
2022-02-28 17:50:45.005 [TRC] CORE: notify: |DATA| (epoch) - Index: 109735883
2022-02-28 17:50:52.394 [WRN] CORE: notify: |WARNING| (notify) Market suspended - Trading for market dcr_btc at 127.0.0.1:17273 is now suspended.
2022-02-28 17:50:52.398 [ERR] CORE[wss://127.0.0.1:17273/ws]: read error (websocket: close 1006 (abnormal closure): unexpected EOF), attempting reconnection
2022-02-28 17:50:52.398 [DBG] CORE: notify: |POKE| (conn) Server disconnect - 127.0.0.1:17273 is disconnected
2022-02-28 17:50:52.398 [INF] CORE[wss://127.0.0.1:17273/ws]: Attempting to reconnect to wss://127.0.0.1:17273/ws...
2022-02-28 17:50:52.398 [ERR] CORE[wss://127.0.0.1:17273/ws]: Reconnect failed. Scheduling reconnect to wss://127.0.0.1:17273/ws in 5.0 seconds.
2022-02-28 17:50:55.298 [TRC] WEB[WS]: message of type 1 received for route unmarket
2022-02-28 17:50:56.778 [TRC] WEB[WS]: message of type 1 received for route unmarket
2022-02-28 17:50:56.778 [CRT] WEB[WS][127.0.0.1:55426]: Uh-oh! Panic while handling message from 127.0.0.1:55426.

Message:

&msgjson.Message{Type:0x1, Route:"unmarket", ID:0x3, Payload:json.RawMessage{0x7b, 0x7d}}

Panic:

runtime error: invalid memory address or nil pointer dereference

Stack:

goroutine 159 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
decred.org/dcrdex/dex/ws.(*WSLink).handleMessage.func1()
	/home/joe/git/dcrdex/dex/ws/wslink.go:212 +0x58
panic({0x110a740, 0x1ebc590})
	/usr/lib/go/src/runtime/panic.go:1038 +0x215
decred.org/dcrdex/client/websocket.wsUnmarket(0x10faaa0, 0xc000202c30, 0xc016202bf8)
	/home/joe/git/dcrdex/client/websocket/websocket.go:355 +0x7b
decred.org/dcrdex/client/websocket.(*Server).handleMessage(0xc00058e000, 0xc0009e1340, 0xc0009e1340)
	/home/joe/git/dcrdex/client/websocket/websocket.go:196 +0x1c9
decred.org/dcrdex/client/websocket.(*Server).connect.func1(0x555c85)
	/home/joe/git/dcrdex/client/websocket/websocket.go:132 +0x2a
decred.org/dcrdex/dex/ws.(*WSLink).handleMessage(0xc00048c380, 0xc0009e1340)
	/home/joe/git/dcrdex/dex/ws/wslink.go:218 +0x73
decred.org/dcrdex/dex/ws.(*WSLink).inHandler(0xc00048c380, {0x1703d58, 0xc00025a580})
	/home/joe/git/dcrdex/dex/ws/wslink.go:269 +0x1f7
created by decred.org/dcrdex/dex/ws.(*WSLink).Connect
	/home/joe/git/dcrdex/dex/ws/wslink.go:173 +0x29d



2022-02-28 17:50:57.399 [INF] CORE[wss://127.0.0.1:17273/ws]: Attempting to reconnect to wss://127.0.0.1:17273/ws...
2022-02-28 17:50:57.399 [ERR] CORE[wss://127.0.0.1:17273/ws]: Reconnect failed. Scheduling reconnect to wss://127.0.0.1:17273/ws in 10.0 seconds.
2022-02-28 17:51:03.426 [TRC] WEB[WS][127.0.0.1:55426]: Sent 83 and dropped 0 messages to 127.0.0.1:55426 before shutdown.
```

**Comment by bgptr** [comment]
Looking into this
