### ISSUE TITLE
market.js: this.tmpl undefined in setConnected

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#1521]
![image](https://user-images.githubusercontent.com/9373513/158643729-bb1537e8-43ec-4617-a26b-f0764ea47962.png)

![image](https://user-images.githubusercontent.com/9373513/158643808-6cea0ff8-e343-4fca-bfa4-c21ead73da36.png)

**Comment by JoeGruffins** [comment]
Hmm, something happened, but unrelated to these changes I think. Related to eth. When running the simnet setup script:
```
2022-03-17 12:02:38.761 [DBG] RPC: authenticated user with ip: 127.0.0.1:34192
2022-03-17 12:02:38.761 [TRC] CORE: wallet status requested for unknown asset 60 -> eth
2022-03-17 12:02:38.793 [INF] CORE: Initializing a built-in eth wallet
2022/03/17 12:02:38 http: panic serving 127.0.0.1:34192: runtime error: slice bounds out of range [-1:]
goroutine 1296 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/go/src/net/http/server.go:1802 +0xb9
panic({0x121cf60, 0xc000392258})
        /usr/lib/go/src/runtime/panic.go:1047 +0x266
github.com/go-chi/chi/v5/middleware.prettyStack.decorateFuncCallLine({}, {0xc00cd38194, 0x450d34}, 0x6e, 0x6)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:130 +0x545
github.com/go-chi/chi/v5/middleware.prettyStack.decorateLine({}, {0xc00cd38194, 0xc00020c000}, 0x20, 0x1)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:106 +0x15d
github.com/go-chi/chi/v5/middleware.prettyStack.parse({}, {0xc000568000, 0xcca, 0xe98abf}, {0x111f9a0, 0x16e7310})
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:89 +0x510
github.com/go-chi/chi/v5/middleware.PrintPrettyStack({0x111f9a0, 0x16e7310})
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:46 +0x45
github.com/go-chi/chi/v5/middleware.Recoverer.func1.1()
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:30 +0xdd
panic({0x111f9a0, 0x16e7310})
        /usr/lib/go/src/runtime/panic.go:1038 +0x215
decred.org/dcrdex/client/core.(*Core).loadWallet(0xc0001f0300, 0xc00036c0f0)
        /home/joe/git/dcrdex/client/core/core.go:1883 +0x2b4
decred.org/dcrdex/client/core.(*Core).CreateWallet(0xc0001f0300, {0xc000391060, 0x3, 0x3}, {0x1fd5890, 0x0, 0x0}, 0xc0007ca320)
        /home/joe/git/dcrdex/client/core/core.go:1749 +0x54f
decred.org/dcrdex/client/rpcserver.handleNewWallet(0xc000400230, 0xc000274b40)
        /home/joe/git/dcrdex/client/rpcserver/handlers.go:177 +0x24d
decred.org/dcrdex/client/rpcserver.(*RPCServer).handleRequest(0xc00082e8c0, 0xc00082e8c0)
        /home/joe/git/dcrdex/client/rpcserver/rpcserver.go:314 +0x295
decred.org/dcrdex/client/rpcserver.(*RPCServer).parseHTTPRequest(0xc00017cc00, {0x170c3e0, 0xc0002382a0}, 0xc00082e8c0)
        /home/joe/git/dcrdex/client/rpcserver/rpcserver.go:320 +0x35
decred.org/dcrdex/client/rpcserver.(*RPCServer).handleJSON(0x23, {0x170c3e0, 0xc0002382a0}, 0xc00047a000)
        /home/joe/git/dcrdex/client/rpcserver/rpcserver.go:165 +0x27a
net/http.HandlerFunc.ServeHTTP(0x11105a0, {0x170c3e0, 0xc0002382a0}, 0xc000390af5)
        /usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000032600, {0x170c3e0, 0xc0002382a0}, 0xc00047a000)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:437 +0x1f9
net/http.HandlerFunc.ServeHTTP(0xc00038c000, {0x170c3e0, 0xc0002382a0}, 0xc000384ab0)
        /usr/lib/go/src/net/http/server.go:2047 +0x2f
decred.org/dcrdex/client/rpcserver.(*RPCServer).authMiddleware.func1({0x170c3e0, 0xc0002382a0}, 0xc00047a000)
        /home/joe/git/dcrdex/client/rpcserver/rpcserver.go:350 +0x203
net/http.HandlerFunc.ServeHTTP(0xc00047a000, {0x170c3e0, 0xc0002382a0}, 0x0)
        /usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi/v5/middleware.RealIP.func1({0x170c3e0, 0xc0002382a0}, 0xc00047a000)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/realip.go:34 +0x9e
net/http.HandlerFunc.ServeHTTP(0x100000000000000, {0x170c3e0, 0xc0002382a0}, 0x90)
        /usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi/v5/middleware.Recoverer.func1({0x170c3e0, 0xc0002382a0}, 0x1ee6201)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:37 +0x83
net/http.HandlerFunc.ServeHTTP(0x17209b8, {0x170c3e0, 0xc0002382a0}, 0x1ee62e0)
        /usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000032600, {0x170c3e0, 0xc0002382a0}, 0xc000207800)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:88 +0x442
net/http.serverHandler.ServeHTTP({0x170a1f8}, {0x170c3e0, 0xc0002382a0}, 0xc000207800)
        /usr/lib/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0000d8320, {0x1720a60, 0xc000278150})
        /usr/lib/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:3034 +0x4e8
```

**Comment by JoeGruffins** [comment]
Whoops, meant to comment on #1522
