### ISSUE TITLE
deadlock in client/core TestRegister with -race

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#158]
in `client/core`, `TestRegister` seems to deadlock with:

    go test -v -race -count 1

**Comment by chappjc** [comment]
From SIGABRT:```


goroutine 0 [idle]:
runtime.futex(0xf14548, 0x80, 0x0, 0x0, 0x0, 0x7fb0433452a8, 0x7fb043345300, 0x7fb0433452a8, 0x7ffcc08e7088, 0x43384f, ...)
	/home/jon/go113/src/runtime/sys_linux_amd64.s:535 +0x21
runtime.futexsleep(0xf14548, 0x7fb000000000, 0xffffffffffffffff)
	/home/jon/go113/src/runtime/os_linux.go:44 +0x46
runtime.notesleep(0xf14548)
	/home/jon/go113/src/runtime/lock_futex.go:151 +0x9f
runtime.stopm()
	/home/jon/go113/src/runtime/proc.go:1928 +0xc0
runtime.findrunnable(0xc000026000, 0x0)
	/home/jon/go113/src/runtime/proc.go:2391 +0x53f
runtime.schedule()
	/home/jon/go113/src/runtime/proc.go:2524 +0x2be
runtime.park_m(0xc000078300)
	/home/jon/go113/src/runtime/proc.go:2610 +0x9d
runtime.mcall(0x0)
	/home/jon/go113/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [chan receive, 3 minutes]:
testing.(*T).Run(0xc0000fe400, 0xa20704, 0xc, 0xb858a0, 0x1)
	/home/jon/go113/src/testing/testing.go:961 +0x68a
testing.runTests.func1(0xc0000fe400)
	/home/jon/go113/src/testing/testing.go:1202 +0xa7
testing.tRunner(0xc0000fe400, 0xc00011fc38)
	/home/jon/go113/src/testing/testing.go:909 +0x19a
testing.runTests(0xc00000e6c0, 0xf06e00, 0x4, 0x4, 0x0)
	/home/jon/go113/src/testing/testing.go:1200 +0x522
testing.(*M).Run(0xc000470780, 0x0)
	/home/jon/go113/src/testing/testing.go:1117 +0x300
decred.org/dcrdex/client/core.TestMain.func1(0x0)
	/home/jon/github/decred/dcrdex/client/core/core_test.go:383 +0x7c
decred.org/dcrdex/client/core.TestMain(0xc000470780)
	/home/jon/github/decred/dcrdex/client/core/core_test.go:385 +0x292
main.main()
	_testmain.go:48 +0x224

goroutine 44 [chan receive, 3 minutes]:
decred.org/dcrdex/client/core.TestRegister.func5()
	/home/jon/github/decred/dcrdex/client/core/core_test.go:679 +0x9d
decred.org/dcrdex/client/core.TestRegister(0xc0001ae000)
	/home/jon/github/decred/dcrdex/client/core/core_test.go:683 +0xaa0
testing.tRunner(0xc0001ae000, 0xb858a0)
	/home/jon/go113/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/home/jon/go113/src/testing/testing.go:960 +0x652


```
