### ISSUE TITLE
client: btc spv wallet panic during recovery

### ISSUE THREAD

**Issue by ukane-philemon** [decred/dcrdex#1881]
I haven't used my btc spv wallet for some time, then today I tried to use it and it refused to connect with the error message `wallet not found`. Then, I attempted to recover the wallet and ended up with this panic.
```
2022/10/01 23:24:31 http: panic serving 127.0.0.1:54464: runtime error: slice bounds out of range [-1:]
goroutine 76 [running]:
net/http.(*conn).serve.func1()
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:1850 +0xbf
panic({0x5364940, 0xc0002acab0})
        /usr/local/Cellar/go/1.19/libexec/src/runtime/panic.go:890 +0x262
github.com/go-chi/chi/v5/middleware.prettyStack.decorateFuncCallLine({}, {0xc0060e36b4, 0x1d}, 0x46?, 0x6)
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:130 +0x545
github.com/go-chi/chi/v5/middleware.prettyStack.decorateLine({}, {0xc0060e36b4?, 0xc00098f000?}, 0xd0?, 0x1?)
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:106 +0x15d
github.com/go-chi/chi/v5/middleware.prettyStack.parse({}, {0xc0007be000, 0x144f, 0x4f170ff?}, {0x5206a80, 0x68a45c0})
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:89 +0x4d5
github.com/go-chi/chi/v5/middleware.PrintPrettyStack({0x5206a80, 0x68a45c0})
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:46 +0x45
github.com/go-chi/chi/v5/middleware.Recoverer.func1.1()
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:30 +0xdd
panic({0x5206a80, 0x68a45c0})
        /usr/local/Cellar/go/1.19/libexec/src/runtime/panic.go:884 +0x212
github.com/btcsuite/btcwallet/wallet.(*Wallet).AccountProperties(0x0, {0x14018?, 0xc0?}, 0x0)
        /Users/philemon/go/pkg/mod/github.com/btcsuite/btcwallet@v0.15.1/wallet/wallet.go:1820 +0x21
decred.org/dcrdex/client/asset/btc.(*spvWallet).numDerivedAddresses(0xc0000d6370)
        /Users/philemon/Desktop/Decred/dcrdex/client/asset/btc/spv.go:1366 +0x8d
decred.org/dcrdex/client/asset/btc.(*ExchangeWalletSPV).GetRecoveryCfg(0xc00012f7b8?)
        /Users/philemon/Desktop/Decred/dcrdex/client/asset/btc/btc.go:848 +0x3c
decred.org/dcrdex/client/core.(*Core).RecoverWallet(0xc00017d680, 0x7a4c000?, {0xc0006d0398?, 0x512a440?, 0xc007a16040?}, 0x0)
        /Users/philemon/Desktop/Decred/dcrdex/client/core/core.go:2617 +0x58f
decred.org/dcrdex/client/webserver.(*WebServer).apiRecoverWallet(0xc0004e0480, {0x5e25b48, 0xc007a4c000}, 0xc0065f8600?)
        /Users/philemon/Desktop/Decred/dcrdex/client/webserver/api.go:252 +0xe5
net/http.HandlerFunc.ServeHTTP(0xc00024b570?, {0x5e25b48?, 0xc007a4c000?}, 0xc00737e780?)
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:2109 +0x2f
decred.org/dcrdex/client/webserver.(*WebServer).rejectUnauthed.func1({0x5e25b48, 0xc007a4c000}, 0x1?)
        /Users/philemon/Desktop/Decred/dcrdex/client/webserver/middleware.go:119 +0x6a
net/http.HandlerFunc.ServeHTTP(0xc00737e780?, {0x5e25b48?, 0xc007a4c000?}, 0xc0072a2580?)
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0x51f17c0?, {0x5e25b48?, 0xc007a4c000?}, 0xc0006d02e0?)
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/chain.go:31 +0x2c
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc00627e720, {0x5e25b48, 0xc007a4c000}, 0xc0079ec000)
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:437 +0x1f9
net/http.HandlerFunc.ServeHTTP(0x51f2540?, {0x5e25b48?, 0xc007a4c000?}, 0x10?)
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.AllowContentType.func1.1({0x5e25b48, 0xc007a4c000}, 0xc0079ec000)
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/content_type.go:41 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc00024b6f8?, {0x5e25b48?, 0xc007a4c000?}, 0xc00024b6d8?)
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc00627e720, {0x5e25b48, 0xc007a4c000}, 0xc0079ec000)
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:71 +0x355
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x5e25b48, 0xc007a4c000}, 0xc0079ec000)
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:312 +0x19c
net/http.HandlerFunc.ServeHTTP(0x51f17c0?, {0x5e25b48?, 0xc007a4c000?}, 0xc00013cb05?)
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000220540, {0x5e25b48, 0xc007a4c000}, 0xc0079ec000)
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:437 +0x1f9
net/http.HandlerFunc.ServeHTTP(0x5e26c00?, {0x5e25b48?, 0xc007a4c000?}, 0x5e169c0?)
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:2109 +0x2f
decred.org/dcrdex/client/webserver.(*WebServer).authMiddleware.func1({0x5e25b48, 0xc007a4c000}, 0xc0004be900)
        /Users/philemon/Desktop/Decred/dcrdex/client/webserver/middleware.go:49 +0x26d
net/http.HandlerFunc.ServeHTTP(0x10?, {0x5e25b48?, 0xc007a4c000?}, 0x8?)
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.Recoverer.func1({0x5e25b48?, 0xc007a4c000?}, 0xc0004cc420?)
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:37 +0x83
net/http.HandlerFunc.ServeHTTP(0x5326a00?, {0x5e25b48?, 0xc007a4c000?}, 0xe?)
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:2109 +0x2f
decred.org/dcrdex/client/webserver.(*WebServer).securityMiddleware.func1({0x5e25b48, 0xc007a4c000}, 0x68a4101?)
        /Users/philemon/Desktop/Decred/dcrdex/client/webserver/middleware.go:34 +0x4ed
net/http.HandlerFunc.ServeHTTP(0x5e26b58?, {0x5e25b48?, 0xc007a4c000?}, 0x68a41d0?)
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000220540, {0x5e25b48, 0xc007a4c000}, 0xc0004be800)
        /Users/philemon/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:88 +0x310
net/http.serverHandler.ServeHTTP({0x5e23148?}, {0x5e25b48, 0xc007a4c000}, 0xc0004be800)
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc000436000, {0x5e26c00, 0xc006f7d830})
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.19/libexec/src/net/http/server.go:3102 +0x4db
```

I think the panic did come from this line.
```
github.com/btcsuite/btcwallet/wallet.(*Wallet).AccountProperties(0x0, {0x14018?, 0xc0?}, 0x0)
        /Users/philemon/go/pkg/mod/github.com/btcsuite/btcwallet@v0.15.1/wallet/wallet.go:1820 +0x21
decred.org/dcrdex/client/asset/btc.(*spvWallet).numDerivedAddresses(0xc0000d6370)
        /Users/philemon/Desktop/Decred/dcrdex/client/asset/btc/spv.go:1366 +0x8d
```

**Comment by ukane-philemon** [comment]
EDIT: I commented out the code line generating the panic to quickly test if I can recover the wallet. And It worked. I successfully recovered my btc spv wallet in 28min.
https://github.com/decred/dcrdex/blob/master/client/asset/btc/btc.go#L850-L855

**Comment by chappjc** [comment]
Definitely return a nil `recoveryCfg`, but I'd like to understand what happened leading up to this, before the recovery attempt.
Lets understand what gave `wallet not found`, and how `w.Wallet` was nil when calling the recovery method.

**Comment by ukane-philemon** [comment]
> Lets understand what gave wallet not found, and how w.Wallet was nil when calling the recovery method.

```
2022-10-01 19:36:39.614 [INF] CORE: Loaded eth wallet configuration.
2022-10-01 19:36:39.614 [INF] CORE: successfully loaded 3 of 3 wallets
2022-10-01 19:36:39.614 [INF] CORE: Successfully connected to 0 out of 1 DEX servers
....
2022-10-01 19:38:17.197 [INF] CORE: Connecting wallet for eth
2022-10-01 19:38:17.197 [INF] CORE: Connecting wallet for btc
2022-10-01 19:38:17.197 [INF] CORE: Connecting wallet for dcr
2022-10-01 19:38:17.204 [ERR] CORE: Unable to connect to btc wallet (start and sync wallets BEFORE starting dex!): connectWallet: connect failure: wallet not found
```
The logs show `successfully loaded 3 of 3 wallets` but failed to connect to the btc wallet.
I tried to manually connect to the wallet and got the same `wallet not found` error. Btw the wallet was not disabled. Then I tried recovery and recovery does not currently check if the wallet is connected which will end up calling a method on a nil `w.Wallet`.

**Comment by chappjc** [comment]
Will have to dig into the code to discover how it's possible not to be "connected" to a native/built-in wallet.

Please also check the neutrino log in assetdb folder.

**Comment by ukane-philemon** [comment]
```
022-10-02 00:14:04.803 [INF] BTCW: Opened wallet
2022-10-02 00:32:54.149 [INF] BTCW: Opened wallet
2022-10-02 00:32:54.282 [INF] NTRNO: Loaded 0 addresses from file '/Users/philemon/Desktop/testfee/testnet/assetdb/btc/testnet3/spv/peers.json'
2022-10-02 00:32:54.282 [DBG] NTRNO: Starting block notifications subscription manager
2022-10-02 00:32:54.282 [DBG] NTRNO: Waiting for peer connection...
2022-10-02 00:32:54.282 [INF] NTRNO: Registering block subscription: id=1
2022-10-02 00:32:54.283 [DBG] NTRNO: Delivering backlog of block notifications: id=1, start_height=0, end_height=0
2022-10-02 00:32:54.283 [INF] NTRNO: Broadcaster now active
```

Nothing prior to when I finally got to start the recovery.

**Comment by ukane-philemon** [comment]
> Will have to dig into the code to discover how it's possible not to be "connected" to a native/built-in wallet.

An spv wallet is considered `connected` in `core` if the `xcWallet.hookedUp` is set to true? if the wallet can't be found it can't be opened(wallet set up)?

**Comment by JoeGruffins** [comment]
Are you able to reproduce the original error where you can't enable? I can't make it happen on master. It looks like eth's `shutdown` will release any locks on the data dir and db. If it doesn't then I guess the problem is there. Are you sure your wallet just wasn't able to shutdown properly there?

I could be wrong, but my assumption is that the asset driver's `Open` only ever happens once, and then `Connect` also only happens once and that wallet is dead after connect's ctx is canceled and needs another `Open` and `Connect`. The difference being `Connect` stuff needs a `context.Context`. If this assumption is correct then moving between the two should not matter.
