### ISSUE TITLE
client: Panic if unable to connect to dex.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1989]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x12b87ad]

goroutine 95 [running]:
decred.org/dcrdex/client/core.(*Core).refundExpiredBonds(0xc000524c00, {0x214ee78, 0xc0005075c0})
        /home/joe/git/dcrdex/client/core/bond.go:62 +0x16d
decred.org/dcrdex/client/core.(*Core).watchExpiredBonds(0x0?, {0x214ee78, 0xc0005075c0})
        /home/joe/git/dcrdex/client/core/bond.go:42 +0xa8
decred.org/dcrdex/client/core.(*Core).Run.func3()
        /home/joe/git/dcrdex/client/core/core.go:1544 +0x66
created by decred.org/dcrdex/client/core.(*Core).Run
        /home/joe/git/dcrdex/client/core/core.go:1542 +0x5ca
```

To reproduce on simnet, start up the harness and register with a client. Shut the client and server down and start the client and wait a bit.

**Comment by chappjc** [comment]
Darn nil cfg.  Thanks for reporting the full call stack.

**Comment by chappjc** [comment]
If this is holding up your work on 1733, I think this will address it, otherwise I'll see to it in the next bonds PR:

```diff
diff --git a/client/core/bond.go b/client/core/bond.go
index ab3f7594d..51ea91962 100644
--- a/client/core/bond.go
+++ b/client/core/bond.go
@@ -57,8 +57,11 @@ func (c *Core) refundExpiredBonds(ctx context.Context) {
        }
 
        for _, dc := range c.dexConnections() {
-
                dc.cfgMtx.RLock()
+               if dc.cfg == nil {
+                       dc.cfgMtx.RUnlock()
+                       continue
+               }
                lockTimeThresh := now + int64(dc.cfg.BondExpiry)
                dc.cfgMtx.RUnlock()
```

**Comment by JoeGruffins** [comment]
Not holding up 1733, will let you fix it.
