### ISSUE TITLE
client: nil pointer dereference ecountered in `core.refundExpiredBonds`

### ISSUE THREAD

**Issue by ukane-philemon** [decred/dcrdex#1999]
I've hit a panic, and It came from here. https://github.com/decred/dcrdex/blob/master/client/core/bond.go#L62

I was doing a first-time login when I hit that panic, and it seems `dc.cfg` was not populated when that line was hit.

```
2022-12-16 15:25:35.237 [INF] CORE[bch][SPV]: Synchronizing wallet with network...
2022-12-16 15:25:35.239 [INF] CORE[bch]: Connected wallet with current best block 000000001dd410c49a788668ce26751718cc797474d3152a5fc073dd44fd9f7b (0)
2022-12-16 15:25:37.898 [DBG] CORE[eth][ETH][RPC]: Connected with 1 of 1 RPC servers
2022-12-16 15:25:37.933 [INF] CORE[eth][ETH][TXDB]: All 0 tables opened in 0s

2022-12-16 15:25:37.942 [INF] CORE[eth][ETH][TXDB]: Replaying file id: 0 at offset: 0

2022-12-16 15:25:37.942 [INF] CORE[eth][ETH][TXDB]: Replay took: 13.128µs

2022-12-16 15:25:37.942 [DBG] CORE[eth][ETH][TXDB]: Value log discard stats empty
2022-12-16 15:25:37.942 [INF] CORE[eth][ETH]: Connected to geth, at height 8145872
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x100ebb98d]

goroutine 29 [running]:
decred.org/dcrdex/client/core.(*Core).refundExpiredBonds(0xc0000c4a00, {0x101d6a518, 0xc000396b80})
        /Users/philemon/Desktop/Decred/dcrdex/client/core/bond.go:62 +0x16d
decred.org/dcrdex/client/core.(*Core).watchExpiredBonds(0x0?, {0x101d6a518, 0xc000396b80})
        /Users/philemon/Desktop/Decred/dcrdex/client/core/bond.go:42 +0xa8
decred.org/dcrdex/client/core.(*Core).Run.func3()
        /Users/philemon/Desktop/Decred/dcrdex/client/core/core.go:1561 +0x66
created by decred.org/dcrdex/client/core.(*Core).Run
        /Users/philemon/Desktop/Decred/dcrdex/client/core/core.go:1559 +0x5ca
```

**Comment by chappjc** [comment]
Dup of https://github.com/decred/dcrdex/issues/1989.
Fix going into next PR.  I'll make a special fix PR though to get rid of it now.
