### ISSUE TITLE
client/web: Panic while updating to master.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2029]
I attempted updating my personal mainnet dexc to master (#1996 actually). I have been on v0.5 I think. Attempting to start up on web after updating getting a panic. Seems I am unable to view markets:

```
2023-01-05 11:06:03.080 [INF] DEXC: dexc version 0.6.0-pre+88692db99 (Go version go1.19.4)
2023-01-05 11:06:03.080 [INF] DEXC: Logging with UTC time stamps. Current local time is 11:06:03 UTC
2023-01-05 11:06:03.080 [INF] DEXC: dexc starting for network: mainnet
2023-01-05 11:06:03.080 [INF] DEXC: Swap locktimes config: maker 20h0m0s, taker 8h0m0s
2023-01-05 11:06:03.083 [INF] CORE[DB]: Started database (version = 6, file = *redacted*)
2023-01-05 11:06:03.083 [DBG] CORE: Using locale printer for "en-US"
2023-01-05 11:06:03.083 [DBG] CORE: new client core created
2023-01-05 11:06:03.083 [INF] CORE: Starting DEX client core
2023-01-05 11:06:03.085 [INF] CORE: Loaded btc wallet configuration.
2023-01-05 11:06:03.089 [INF] CORE[dcr][RPC]: Setting up rpc client to communicate with dcrwallet at *redacted* with TLS certificate "*redacted*".
2023-01-05 11:06:03.089 [INF] CORE: Loaded dcr wallet configuration.
2023-01-05 11:06:04.396 [DBG] CORE: notify: |POKE| (conn) Server connected - dex.decred.org:7232 is connected
2023-01-05 11:06:04.617 [INF] CORE: Server dex.decred.org:7232 supports API version 0.
2023-01-05 11:06:04.617 [DBG] CORE: Server dex.decred.org:7232 broadcast timeout 22m0s. Tick interval 2m45s
2023-01-05 11:06:04.617 [INF] CORE: Connected to DEX server at dex.decred.org:7232 and listening for messages.
2023-01-05 11:06:04.617 [INF] CORE: Connected to 1 of 1 DEX servers
2023-01-05 11:06:04.618 [INF] CORE: Loaded 1 active orders.
2023-01-05 11:06:04.618 [INF] CORE: Loaded 0 active match orders
2023-01-05 11:06:04.618 [WRN] CORE: 

         ****  IMPORTANT: You have 1 active order on dex.decred.org:7232. LOGIN immediately!  **** 

2023-01-05 11:06:04.618 [DBG] CORE: starting fiat rate fetching
2023-01-05 11:06:04.618 [DBG] WEB: Using embedded site resources.
2023-01-05 11:06:04.620 [INF] WEB: Using language en-US
2023-01-05 11:06:04.621 [INF] WEB: Using embedded HTML templates
2023-01-05 11:06:04.835 [INF] WEB: Web server listening on *redacted*

        ****  OPEN IN YOUR BROWSER TO LOGIN AND TRADE  --->  http://*redacted*  ****

2023-01-05 11:06:16.974 [INF] CORE: Connecting wallet for btc
2023-01-05 11:06:16.974 [INF] CORE: Connecting wallet for dcr
2023-01-05 11:06:16.998 [INF] CORE[dcr][RPC]: Connected to dcrwallet (JSON-RPC API v9.0.0) proxying dcrd (JSON-RPC API v8.0.0)
2023-01-05 11:06:17.010 [INF] CORE[btc]: Connected wallet with current best block 000000000000000000009aecd7363299a1b4b5f2d4207b3d2406c852a4b142fb (770474)
2023-01-05 11:06:17.032 [INF] CORE: Connected to 2 of 2 wallets.
2023-01-05 11:06:17.032 [INF] CORE: Loaded 1 active orders.
2023-01-05 11:06:17.032 [INF] CORE: Loaded 0 active match orders
2023-01-05 11:06:17.033 [INF] CORE: Loaded 1 incomplete orders with DEX dex.decred.org:7232
2023-01-05 11:06:26.003 [DBG] CORE[dcr]: tip change: 726564 (000000000000000019bec07e40812aa02c7de2b16b09bce48c3db70c03854214) => 726565 (00000000000000003d500cfef357d77c1ce9802926594dc4b8fec9fd28b9de72)
2023-01-05 11:06:26.345 [ERR] CORE: notify: |ERROR| (order) Order coin fetch error - Source coins retrieval error for order 6d7e4f50 (dcr): funding coins not found: 81dd5dc905fa8777f94d686951003a80fad043b9ed5bfcfd155771daee93ab8b:0 - Order: 6d7e4f503da01818577db2b209c251c7c793543c5130d8071b1f9866d6735ec8
2023-01-05 11:06:26.346 [WRN] CORE: Check the status of your DCR wallet and the coins logged above! Resolve the wallet issue if possible and restart the DEX client.
2023-01-05 11:06:26.346 [WRN] CORE: Unfunded order 6d7e4f503da01818577db2b209c251c7c793543c5130d8071b1f9866d6735ec8 will be canceled on connect, but 0 active matches need funding coins!
2023-01-05 11:06:28.030 [INF] CORE: Authenticated connection to dex.decred.org:7232, acct 1c338fcf47682023249254f2705d9823e53a5ad81fd23af22782b2b22a1e7f7d, 0 active bonds, 0 active orders, 0 active matches, score -55, tier 1
2023-01-05 11:06:28.030 [DBG] CORE: Requesting statuses for 1 orders from DEX dex.decred.org:7232
2023-01-05 11:06:28.260 [WRN] CORE: Order 6d7e4f503da01818577db2b209c251c7c793543c5130d8071b1f9866d6735ec8 updated from recorded status "booked" to new status "revoked" reported by DEX dex.decred.org:7232
2023-01-05 11:06:28.263 [WRN] CORE: notify: |WARNING| (order) Order status update - Status of order 6d7e4f50 revised from booked to revoked - Order: 6d7e4f503da01818577db2b209c251c7c793543c5130d8071b1f9866d6735ec8
2023-01-05 11:06:28.263 [DBG] CORE: notify: |POKE| (dex_auth) Orders reconciled with DEX - Statuses updated for 1 orders.
2023-01-05 11:06:50.024 [DBG] WEB[WS]: New websocket client *redacted*
2023-01-05 11:06:50.026 [DBG] CORE: Subscribing to the dcr_btc order book for dex.decred.org:7232
2023-01-05 11:06:50.152 [DBG] WEB[WS]: New websocket client *redacted*
2023-01-05 11:06:50.448 [DBG] CORE: Subscribing to the dcr_btc order book for dex.decred.org:7232
2023-01-05 11:06:50.449 [CRT] WEB[WS][*redacted*]: Uh-oh! Panic while handling message from *redacted*.

Message:

&msgjson.Message{Type:0x1, Route:"loadmarket", ID:0x1, Payload:json.RawMessage{0x7b, 0x22, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x3a, 0x22, 0x64, 0x65, 0x78, 0x2e, 0x64, 0x65, 0x63, 0x72, 0x65, 0x64, 0x2e, 0x6f, 0x72, 0x67, 0x3a, 0x37, 0x32, 0x33, 0x32, 0x22, 0x2c, 0x22, 0x62, 0x61, 0x73, 0x65, 0x22, 0x3a, 0x34, 0x32, 0x2c, 0x22, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x22, 0x3a, 0x30, 0x7d}}

Panic:

unaligned 64-bit atomic operation

Stack:

goroutine 459 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x78
decred.org/dcrdex/dex/ws.(*WSLink).handleMessage.func1()
        /home/joe/git/dcrdex/dex/ws/wslink.go:228 +0x50
panic({0xd2f2f8, 0x1799340})
        /usr/lib/go/src/runtime/panic.go:884 +0x23c
runtime/internal/atomic.panicUnaligned()
        /usr/lib/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x386cc64, 0xa)
        /usr/lib/go/src/runtime/internal/atomic/atomic_arm.s:291 +0x14
decred.org/dcrdex/client/orderbook.(*OrderBook).Reset(0x386cbe0, 0x3cd8d00)
        /home/joe/git/dcrdex/client/orderbook/orderbook.go:245 +0x70
decred.org/dcrdex/client/orderbook.(*OrderBook).Sync(0x386cbe0, 0x3cd8d00)
        /home/joe/git/dcrdex/client/orderbook/orderbook.go:232 +0x78
decred.org/dcrdex/client/core.(*dexConnection).syncBook(0x31ba500, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:420 +0x1f4
decred.org/dcrdex/client/core.(*Core).syncBook(0x3400000, {0x30a1b00, 0x13}, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:541 +0x98
decred.org/dcrdex/client/core.(*Core).SyncBook(0x3400000, {0x30a1b00, 0x13}, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:529 +0x3c
decred.org/dcrdex/client/websocket.loadMarket(0x34ec140, 0x3d16630, 0x3ce60e0)
        /home/joe/git/dcrdex/client/websocket/websocket.go:304 +0x1c8
decred.org/dcrdex/client/websocket.wsLoadMarket(0x34ec140, 0x3d16630, 0x3a65b00)
        /home/joe/git/dcrdex/client/websocket/websocket.go:292 +0x198
decred.org/dcrdex/client/websocket.(*Server).handleMessage(0x34ec140, 0x3d16630, 0x3a65b00)
        /home/joe/git/dcrdex/client/websocket/websocket.go:201 +0x1f0
decred.org/dcrdex/client/websocket.(*Server).connect.func1(0x3a65b00)
        /home/joe/git/dcrdex/client/websocket/websocket.go:140 +0x30
decred.org/dcrdex/dex/ws.(*WSLink).handleMessage(0x3d01b00, 0x3a65b00)
        /home/joe/git/dcrdex/dex/ws/wslink.go:234 +0x70
decred.org/dcrdex/dex/ws.(*WSLink).inHandler(0x3d01b00, {0x179da90, 0x3d16690})
        /home/joe/git/dcrdex/dex/ws/wslink.go:285 +0x218
created by decred.org/dcrdex/dex/ws.(*WSLink).Connect
        /home/joe/git/dcrdex/dex/ws/wslink.go:189 +0x338



2023-01-05 11:06:50.671 [DBG] CORE: Subscribing to the dcr_btc order book for dex.decred.org:7232
2023-01-05 11:06:50.672 [CRT] WEB[WS][*redacted*]: Uh-oh! Panic while handling message from *redacted*.

Message:

&msgjson.Message{Type:0x1, Route:"loadmarket", ID:0x1, Payload:json.RawMessage{0x7b, 0x22, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x3a, 0x22, 0x64, 0x65, 0x78, 0x2e, 0x64, 0x65, 0x63, 0x72, 0x65, 0x64, 0x2e, 0x6f, 0x72, 0x67, 0x3a, 0x37, 0x32, 0x33, 0x32, 0x22, 0x2c, 0x22, 0x62, 0x61, 0x73, 0x65, 0x22, 0x3a, 0x34, 0x32, 0x2c, 0x22, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x22, 0x3a, 0x30, 0x7d}}

Panic:

unaligned 64-bit atomic operation

Stack:

goroutine 401 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x78
decred.org/dcrdex/dex/ws.(*WSLink).handleMessage.func1()
        /home/joe/git/dcrdex/dex/ws/wslink.go:228 +0x50
panic({0xd2f2f8, 0x1799340})
        /usr/lib/go/src/runtime/panic.go:884 +0x23c
runtime/internal/atomic.panicUnaligned()
        /usr/lib/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x386cd04, 0xa)
        /usr/lib/go/src/runtime/internal/atomic/atomic_arm.s:291 +0x14
decred.org/dcrdex/client/orderbook.(*OrderBook).Reset(0x386cc80, 0x3e02b40)
        /home/joe/git/dcrdex/client/orderbook/orderbook.go:245 +0x70
decred.org/dcrdex/client/orderbook.(*OrderBook).Sync(0x386cc80, 0x3e02b40)
        /home/joe/git/dcrdex/client/orderbook/orderbook.go:232 +0x78
decred.org/dcrdex/client/core.(*dexConnection).syncBook(0x31ba500, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:420 +0x1f4
decred.org/dcrdex/client/core.(*Core).syncBook(0x3400000, {0x3030f18, 0x13}, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:541 +0x98
decred.org/dcrdex/client/core.(*Core).SyncBook(0x3400000, {0x3030f18, 0x13}, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:529 +0x3c
decred.org/dcrdex/client/websocket.loadMarket(0x34ec140, 0x3151830, 0x3d84720)
        /home/joe/git/dcrdex/client/websocket/websocket.go:304 +0x1c8
decred.org/dcrdex/client/websocket.wsLoadMarket(0x34ec140, 0x3151830, 0x3665d60)
        /home/joe/git/dcrdex/client/websocket/websocket.go:292 +0x198
decred.org/dcrdex/client/websocket.(*Server).handleMessage(0x34ec140, 0x3151830, 0x3665d60)
        /home/joe/git/dcrdex/client/websocket/websocket.go:201 +0x1f0
decred.org/dcrdex/client/websocket.(*Server).connect.func1(0x3665d60)
        /home/joe/git/dcrdex/client/websocket/websocket.go:140 +0x30
decred.org/dcrdex/dex/ws.(*WSLink).handleMessage(0x3d88780, 0x3665d60)
        /home/joe/git/dcrdex/dex/ws/wslink.go:234 +0x70
decred.org/dcrdex/dex/ws.(*WSLink).inHandler(0x3d88780, {0x179da90, 0x3151890})
        /home/joe/git/dcrdex/dex/ws/wslink.go:285 +0x218
created by decred.org/dcrdex/dex/ws.(*WSLink).Connect
        /home/joe/git/dcrdex/dex/ws/wslink.go:189 +0x338



2023-01-05 11:06:50.889 [DBG] CORE: Subscribing to the dcr_btc order book for dex.decred.org:7232
2023-01-05 11:06:50.890 [CRT] WEB[WS][*redacted*]: Uh-oh! Panic while handling message from *redacted*.

Message:

&msgjson.Message{Type:0x1, Route:"loadcandles", ID:0x2, Payload:json.RawMessage{0x7b, 0x22, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x3a, 0x22, 0x64, 0x65, 0x78, 0x2e, 0x64, 0x65, 0x63, 0x72, 0x65, 0x64, 0x2e, 0x6f, 0x72, 0x67, 0x3a, 0x37, 0x32, 0x33, 0x32, 0x22, 0x2c, 0x22, 0x62, 0x61, 0x73, 0x65, 0x22, 0x3a, 0x34, 0x32, 0x2c, 0x22, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x22, 0x3a, 0x30, 0x2c, 0x22, 0x64, 0x75, 0x72, 0x22, 0x3a, 0x22, 0x35, 0x6d, 0x22, 0x7d}}

Panic:

unaligned 64-bit atomic operation

Stack:

goroutine 459 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x78
decred.org/dcrdex/dex/ws.(*WSLink).handleMessage.func1()
        /home/joe/git/dcrdex/dex/ws/wslink.go:228 +0x50
panic({0xd2f2f8, 0x1799340})
        /usr/lib/go/src/runtime/panic.go:884 +0x23c
runtime/internal/atomic.panicUnaligned()
        /usr/lib/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x386cda4, 0xa)
        /usr/lib/go/src/runtime/internal/atomic/atomic_arm.s:291 +0x14
decred.org/dcrdex/client/orderbook.(*OrderBook).Reset(0x386cd20, 0x3e02c00)
        /home/joe/git/dcrdex/client/orderbook/orderbook.go:245 +0x70
decred.org/dcrdex/client/orderbook.(*OrderBook).Sync(0x386cd20, 0x3e02c00)
        /home/joe/git/dcrdex/client/orderbook/orderbook.go:232 +0x78
decred.org/dcrdex/client/core.(*dexConnection).syncBook(0x31ba500, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:420 +0x1f4
decred.org/dcrdex/client/core.(*Core).syncBook(0x3400000, {0x3030f48, 0x13}, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:541 +0x98
decred.org/dcrdex/client/core.(*Core).SyncBook(0x3400000, {0x3030f48, 0x13}, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:529 +0x3c
decred.org/dcrdex/client/websocket.loadMarket(0x34ec140, 0x3d16630, 0x3db20a8)
        /home/joe/git/dcrdex/client/websocket/websocket.go:304 +0x1c8
decred.org/dcrdex/client/websocket.wsLoadCandles(0x34ec140, 0x3d16630, 0x3db6060)
        /home/joe/git/dcrdex/client/websocket/websocket.go:342 +0x260
decred.org/dcrdex/client/websocket.(*Server).handleMessage(0x34ec140, 0x3d16630, 0x3db6060)
        /home/joe/git/dcrdex/client/websocket/websocket.go:201 +0x1f0
decred.org/dcrdex/client/websocket.(*Server).connect.func1(0x3db6060)
        /home/joe/git/dcrdex/client/websocket/websocket.go:140 +0x30
decred.org/dcrdex/dex/ws.(*WSLink).handleMessage(0x3d01b00, 0x3db6060)
        /home/joe/git/dcrdex/dex/ws/wslink.go:234 +0x70
decred.org/dcrdex/dex/ws.(*WSLink).inHandler(0x3d01b00, {0x179da90, 0x3d16690})
        /home/joe/git/dcrdex/dex/ws/wslink.go:285 +0x218
created by decred.org/dcrdex/dex/ws.(*WSLink).Connect
        /home/joe/git/dcrdex/dex/ws/wslink.go:189 +0x338



2023-01-05 11:06:50.895 [DBG] WEB[WS][*redacted*]: Connection already dead. Not sending Close control message.
2023-01-05 11:06:51.112 [CRT] WEB[WS][*redacted*: Uh-oh! Panic while handling message from *redacted*.

Message:

&msgjson.Message{Type:0x1, Route:"loadcandles", ID:0x2, Payload:json.RawMessage{0x7b, 0x22, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x3a, 0x22, 0x64, 0x65, 0x78, 0x2e, 0x64, 0x65, 0x63, 0x72, 0x65, 0x64, 0x2e, 0x6f, 0x72, 0x67, 0x3a, 0x37, 0x32, 0x33, 0x32, 0x22, 0x2c, 0x22, 0x62, 0x61, 0x73, 0x65, 0x22, 0x3a, 0x34, 0x32, 0x2c, 0x22, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x22, 0x3a, 0x30, 0x2c, 0x22, 0x64, 0x75, 0x72, 0x22, 0x3a, 0x22, 0x35, 0x6d, 0x22, 0x7d}}

Panic:

unaligned 64-bit atomic operation

Stack:

goroutine 401 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x78
decred.org/dcrdex/dex/ws.(*WSLink).handleMessage.func1()
        /home/joe/git/dcrdex/dex/ws/wslink.go:228 +0x50
panic({0xd2f2f8, 0x1799340})
        /usr/lib/go/src/runtime/panic.go:884 +0x23c
runtime/internal/atomic.panicUnaligned()
        /usr/lib/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x386ce44, 0xa)
        /usr/lib/go/src/runtime/internal/atomic/atomic_arm.s:291 +0x14
decred.org/dcrdex/client/orderbook.(*OrderBook).Reset(0x386cdc0, 0x3e02cc0)
        /home/joe/git/dcrdex/client/orderbook/orderbook.go:245 +0x70
decred.org/dcrdex/client/orderbook.(*OrderBook).Sync(0x386cdc0, 0x3e02cc0)
        /home/joe/git/dcrdex/client/orderbook/orderbook.go:232 +0x78
decred.org/dcrdex/client/core.(*dexConnection).syncBook(0x31ba500, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:420 +0x1f4
decred.org/dcrdex/client/core.(*Core).syncBook(0x3400000, {0x3030f78, 0x13}, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:541 +0x98
decred.org/dcrdex/client/core.(*Core).SyncBook(0x3400000, {0x3030f78, 0x13}, 0x2a, 0x0)
        /home/joe/git/dcrdex/client/core/bookie.go:529 +0x3c
decred.org/dcrdex/client/websocket.loadMarket(0x34ec140, 0x3151830, 0x3db2180)
        /home/joe/git/dcrdex/client/websocket/websocket.go:304 +0x1c8
decred.org/dcrdex/client/websocket.wsLoadCandles(0x34ec140, 0x3151830, 0x3db6340)
        /home/joe/git/dcrdex/client/websocket/websocket.go:342 +0x260
decred.org/dcrdex/client/websocket.(*Server).handleMessage(0x34ec140, 0x3151830, 0x3db6340)
        /home/joe/git/dcrdex/client/websocket/websocket.go:201 +0x1f0
decred.org/dcrdex/client/websocket.(*Server).connect.func1(0x3db6340)
        /home/joe/git/dcrdex/client/websocket/websocket.go:140 +0x30
decred.org/dcrdex/dex/ws.(*WSLink).handleMessage(0x3d88780, 0x3db6340)
        /home/joe/git/dcrdex/dex/ws/wslink.go:234 +0x70
decred.org/dcrdex/dex/ws.(*WSLink).inHandler(0x3d88780, {0x179da90, 0x3151890})
        /home/joe/git/dcrdex/dex/ws/wslink.go:285 +0x218
created by decred.org/dcrdex/dex/ws.(*WSLink).Connect
        /home/joe/git/dcrdex/dex/ws/wslink.go:189 +0x338
```

**Comment by JoeGruffins** [comment]
Perhaps this has to do with the raspberry pi I am running on? This is a new one so it's possible I goofed somewhere during installation, but the OS and devices are the same I believe.

```
uname -a
Linux alarmpi 5.15.84-3-rpi-ARCH #1 SMP Wed Jan 4 14:32:52 MST 2023 armv7l GNU/Linux
```

**Comment by JoeGruffins** [comment]
hmm https://pkg.go.dev/sync/atomic#pkg-note-BUG

**Comment by chappjc** [comment]
Yeesh. We have comments about about just that alignment bug all over the place, and we even took steps with these exact fields to do it by putting the fields as the first in a struct.  However:

> The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.

That does not apply to *embedded* structs within an allocated struct.

https://groups.google.com/g/golang-nuts/c/_nHK6P8_lhw/m/CLsj2JRqBAAJ

We need to just move the atomic fields to the top of the struct instead.

**Comment by chappjc** [comment]
fail: https://github.com/decred/dcrdex/blob/63cbc663040c307d9fbd3a6d157f287112f7310e/client/orderbook/orderbook.go#L95-L104

**Comment by JoeGruffins** [comment]
Yes, simply moving that inner struct to the top fixes it.
