### ISSUE TITLE
raspberri pi: Unable to allocate memory for tx history db.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2698]
Today I tried updating my mainnet wallet on a raspberri pi from  dexc version 0.7.0-pre+00c1c7b59 to current master  0.7.0-pre+462dcb6e0 and both my bitcoin and litecoin wallets disappeared. Logs say that I was unable to create the tx history db because of a memory problem.

```
2024-02-10 03:18:41.670 [ERR] CORE: error loading 0 -> btc wallet: error opening wallet: failed to create tx history db: Mmap value log file. Path=/home/joe/finalbig/.dexc/mainnet/assetdb/btc/mainnet/txhistory.db/000000.vlog. Error=cannot allocate memory
2024-02-10 03:18:41.699 [INF] CORE[ltc][TXHISTORYDB]: All 0 tables opened in 0s

2024-02-10 03:18:41.703 [ERR] CORE: error loading 2 -> ltc wallet: error opening wallet: failed to create tx history db: Mmap value log file. Path=/home/joe/finalbig/.dexc/mainnet/assetdb/ltc/mainnet/txhistory.db/000000.vlog. Error=cannot allocate memory
```

free shows ample memory, 3 gigabytes, or does it really need more?
```
$ free
               total        used        free      shared  buff/cache   available
Mem:         3924716      870100      580292         680     2474324     3010320
Swap:              0           0           0
```

Seems like something may be off. Could also be my device.

**Comment by JoeGruffins** [comment]
I changed the option here to FileIO and it loaded https://github.com/decred/dcrdex/blob/462dcb6e0736f6d1c4deaddda85fe6515e0284c0/client/asset/btc/txdb.go#L90

Will watch it so see if there are any problems. Do we want the memory map normally? I would like to change this for use with lower memory devices but can also be a flag.

**Comment by JoeGruffins** [comment]
I doubt related to this issue, but seeing this now too:
```
2024-02-12 07:24:13.247 [ERR] CORE[ltc]: failed to get best block header from ltc node: database isn't correctly mapped
2024-02-12 07:24:13.267 [ERR] CORE[ltc][SPV][NTRNO]: unable to get filter for hash=20865dc09d42b1936d2b8d02c6bc24c4e32a479bfc53b5d3ebe6b32d74fb0414, retrying: database isn't correctly mapped
2024-02-12 07:24:13.368 [ERR] CORE[ltc][SPV][NTRNO]: unable to get filter for hash=20865dc09d42b1936d2b8d02c6bc24c4e32a479bfc53b5d3ebe6b32d74fb0414, retrying: database isn't correctly mapped
2024-02-12 07:24:13.373 [ERR] CORE[btc]: failed to get best block header from btc node: database isn't correctly mapped
```

**Comment by JoeGruffins** [comment]
Maybe unrelated but recording a panic:
```
2024/03/06 02:08:05 http: panic serving 192.168.1.62:50996: runtime error: slice bounds out of range [-1:]
goroutine 10902 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/go/src/net/http/server.go:1850 +0xec
panic({0x1307da8, 0x13096590})
        /usr/lib/go/src/runtime/panic.go:890 +0x2ac
github.com/go-chi/chi/v5/middleware.prettyStack.decorateFuncCallLine({}, {0x11aafa69, 0x1d}, 0x1, 0x8)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:130 +0x510
github.com/go-chi/chi/v5/middleware.prettyStack.decorateLine({}, {0x11aafa69, 0x1d}, 0x1, 0x8)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:106 +0x158
github.com/go-chi/chi/v5/middleware.prettyStack.parse({}, {0xf43c000, 0x1605, 0x2000}, {0x11dddd8, 0x1ea35e0})
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:89 +0x464
github.com/go-chi/chi/v5/middleware.PrintPrettyStack({0x11dddd8, 0x1ea35e0})
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:46 +0x40
github.com/go-chi/chi/v5/middleware.(*defaultLogEntry).Panic(0x141fe190, {0x11dddd8, 0x1ea35e0}, {0xf43a000, 0x148d, 0x2000})
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/logger.go:165 +0x24
github.com/go-chi/chi/v5/middleware.Recoverer.func1.1()
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:28 +0x120
panic({0x11dddd8, 0x1ea35e0})
        /usr/lib/go/src/runtime/panic.go:884 +0x23c
github.com/dgraph-io/badger.(*Txn).Discard(0x16ef27d0)
        /home/joe/go/pkg/mod/github.com/dgraph-io/badger@v1.6.2/txn.go:446 +0xcc
panic({0x124c800, 0x2813d28})
        /usr/lib/go/src/runtime/panic.go:884 +0x23c
github.com/dgraph-io/badger/skl.(*Skiplist).IncrRef(...)
        /home/joe/go/pkg/mod/github.com/dgraph-io/badger@v1.6.2/skl/skl.go:86
github.com/dgraph-io/badger.(*DB).getMemTables(0x4169800)
        /home/joe/go/pkg/mod/github.com/dgraph-io/badger@v1.6.2/db.go:493 +0xd4
github.com/dgraph-io/badger.(*Txn).NewIterator(0x16ef27d0, {0x1, 0x64, 0x1, 0x0, {0x0, 0x0, 0x0}, 0x0, 0x0})
        /home/joe/go/pkg/mod/github.com/dgraph-io/badger@v1.6.2/iterator.go:454 +0x80
decred.org/dcrdex/client/asset/btc.(*BadgerTxDB).GetTxs.func1(0x16ef27d0)
        /home/joe/git/dcrdex/client/asset/btc/txdb.go:262 +0x244
github.com/dgraph-io/badger.(*DB).View(0x4169800, 0x13af08b8)
        /home/joe/go/pkg/mod/github.com/dgraph-io/badger@v1.6.2/txn.go:683 +0xd0
decred.org/dcrdex/client/asset/btc.(*BadgerTxDB).GetTxs(0x4128660, 0xa, 0x0, 0x1)
        /home/joe/git/dcrdex/client/asset/btc/txdb.go:241 +0x70
decred.org/dcrdex/client/asset/btc.(*ExchangeWalletSPV).TxHistory(0x41286b0, 0xa, 0x0, 0x0)
        /home/joe/git/dcrdex/client/asset/btc/btc.go:5373 +0x80
decred.org/dcrdex/client/core.(*xcWallet).TxHistory(0x413e000, 0xa, 0x0, 0x0)
        /home/joe/git/dcrdex/client/core/wallet.go:552 +0x7c
decred.org/dcrdex/client/core.(*Core).TxHistory(0x449cb00, 0x0, 0xa, 0x0, 0x0)
        /home/joe/git/dcrdex/client/core/core.go:5979 +0x144
decred.org/dcrdex/client/webserver.(*WebServer).apiTxHistory(0x42aa150, {0xa6278968, 0x103f2960}, 0x48f6300)
        /home/joe/git/dcrdex/client/webserver/api.go:2023 +0xa8
net/http.HandlerFunc.ServeHTTP(0x42b7258, {0xa6278968, 0x103f2960}, 0x48f6300)
        /usr/lib/go/src/net/http/server.go:2109 +0x34
decred.org/dcrdex/client/webserver.(*WebServer).rejectUnauthed.func1({0xa6278968, 0x103f2960}, 0x48f6300)
        /home/joe/git/dcrdex/client/webserver/middleware.go:132 +0x6c
net/http.HandlerFunc.ServeHTTP(0x47d3890, {0xa6278968, 0x103f2960}, 0x48f6300)
        /usr/lib/go/src/net/http/server.go:2109 +0x34
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0x137ff5a0, {0xa6278968, 0x103f2960}, 0x48f6300)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/chain.go:31 +0x40
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x46cd800, {0xa6278968, 0x103f2960}, 0x48f6300)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:437 +0x264
net/http.HandlerFunc.ServeHTTP(0x42b6d90, {0xa6278968, 0x103f2960}, 0x48f6300)
        /usr/lib/go/src/net/http/server.go:2109 +0x34
github.com/go-chi/chi/v5/middleware.AllowContentType.func1.1({0xa6278968, 0x103f2960}, 0x48f6300)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/content_type.go:41 +0x140
net/http.HandlerFunc.ServeHTTP(0x47d2ee0, {0xa6278968, 0x103f2960}, 0x48f6300)
        /usr/lib/go/src/net/http/server.go:2109 +0x34
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x46cd800, {0xa6278968, 0x103f2960}, 0x48f6300)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:71 +0x378
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0xa6278968, 0x103f2960}, 0x48f6300)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:312 +0x1d8
net/http.HandlerFunc.ServeHTTP(0x47d3b90, {0xa6278968, 0x103f2960}, 0x48f6300)
        /usr/lib/go/src/net/http/server.go:2109 +0x34
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x439c240, {0xa6278968, 0x103f2960}, 0x48f6300)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:437 +0x264
net/http.HandlerFunc.ServeHTTP(0x42b6ae0, {0xa6278968, 0x103f2960}, 0x48f6300)
        /usr/lib/go/src/net/http/server.go:2109 +0x34
github.com/go-chi/chi/v5/middleware.Recoverer.func1({0xa6278968, 0x103f2960}, 0x48f6300)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/recoverer.go:37 +0x8c
net/http.HandlerFunc.ServeHTTP(0x47d29b0, {0xa6278968, 0x103f2960}, 0x48f6300)
        /usr/lib/go/src/net/http/server.go:2109 +0x34
decred.org/dcrdex/client/webserver.(*WebServer).securityMiddleware.func1({0xa6278968, 0x103f2960}, 0x48f6300)
        /home/joe/git/dcrdex/client/webserver/middleware.go:34 +0x4ec
net/http.HandlerFunc.ServeHTTP(0x47d29c0, {0xa6278968, 0x103f2960}, 0x48f6300)
        /usr/lib/go/src/net/http/server.go:2109 +0x34
github.com/go-chi/chi/v5/middleware.RequestLogger.func1.1({0x1eab038, 0x413e5a0}, 0x48f6280)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/middleware/logger.go:57 +0x318
net/http.HandlerFunc.ServeHTTP(0x1293ce10, {0x1eab038, 0x413e5a0}, 0x48f6280)
        /usr/lib/go/src/net/http/server.go:2109 +0x34
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x439c240, {0x1eab038, 0x413e5a0}, 0x48f6180)
        /home/joe/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.1/mux.go:88 +0x324
net/http.serverHandler.ServeHTTP({0x40e2000}, {0x1eab038, 0x413e5a0}, 0x48f6180)
        /usr/lib/go/src/net/http/server.go:2947 +0x2f0
net/http.(*conn).serve(0x4552420, {0x1eabe20, 0x129d6438})
        /usr/lib/go/src/net/http/server.go:1991 +0x654
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:3102 +0x4e0
```

**Comment by JoeGruffins** [comment]
hmm, seeing the same error for the neutrino db's now:
```
[ERR] CORE: Error connecting to ltc wallet: connectWallet: failed to connect ltc wallet: ConnectOnce error: connect failure: unable to create wallet db at "~/.dexc/mainnet/assetdb/ltc/mainnet/neutrino.db": cannot allocate memory
```

Maybe the answer is just make a big swap file.

**Comment by JoeGruffins** [comment]
Added a 4 gig swapfile, but it seems like I cannot have both a btc and ltc light wallet at the same time, the second one is failing with the no memory message. Unsure if due to my changes. Will investigate some on desktop to make sure this isn't a real problem.

**Comment by JoeGruffins** [comment]
Also, I have the btc wallet disabled atm but I see this all over logs after starting an ltc spv wallet "[INF] CORE: Connecting wallet for btc"

**Comment by JoeGruffins** [comment]
I can't seem to reproduce on my desktop. I wonder if its an issue with 32 bit systems. I don't know how to test this, if anyone else has an old computer or an older pi, just try making a btc and ltc spv wallet and see if there is a problem about allocating memory.

**Comment by JoeGruffins** [comment]
I can try one more thing, a virtual machine with limited memory to check if it really is a memory bottleneck.

**Comment by JoeGruffins** [comment]
Appears to be running fine with 2 gigs on mainnet and four spv wallets on a 64 bit system. `$ systemd-run --scope -p MemoryMax=2G --user ./dexc`

It cannot run with only 1 gig but I do not see the error messages regardless. These are fresh wallets however, without any tx history.

**Comment by JoeGruffins** [comment]
It may just be my raspberry pi is the problem. Need someone else to confirm as I don't have any other devices.

**Comment by JoeGruffins** [comment]
I upgraded to a raspberry pi 5 with aarch64 os and the problem seems to have gone away. There may be a problem with 32 bit systems, but maybe it is not worth worrying about. Will close this in a few days if there are no problems on the new pi.
