### ISSUE TITLE
Unexpected panic when LTC is unable to retrieve a block

### ISSUE THREAD

**Issue by ukane-philemon** [decred/dcrdex#2700]
On: dexc-desktop version 0.7.0-pre+462dcb6e0 (Go version go1.21.3 darwin/amd64)

```
panic: unable to synchronize wallet to chain: unable to perform wallet recovery: couldn't retrieve block 1c34af3421ba8f992419b632e32f71472f12d82ab84f3620f41d723b5ce09cbe from network

goroutine 298 [running]:
github.com/ltcsuite/ltcwallet/wallet.(*Wallet).handleChainNotifications(0xc019eb4360)
        /Users/philemon/go/pkg/mod/github.com/ltcsuite/ltcwallet@v0.13.1/wallet/chainntfns.go:117 +0xfd3
created by github.com/ltcsuite/ltcwallet/wallet.(*Wallet).SynchronizeRPC in goroutine 160
        /Users/philemon/go/pkg/mod/github.com/ltcsuite/ltcwallet@v0.13.1/wallet/wallet.go:211 +0x249
exit status 2 

```

My best guess is that I had a poor internet connection at the time and the LTC backend was unable to connect?.

But users shouldn't get this kind of panics.

**Comment by ukane-philemon** [comment]
> Duplicate of https://github.com/decred/dcrdex/issues/2616.

Ah, yh. Missed that.
