### ISSUE TITLE
electrum: Unable to sign transactions on simnet.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#2837]
I was unable to run electron on simnet at the current version `4.3.0a` but was after updating to `4.5.5`. Everything seems to be fine up until signing a transaction. I will get an error from client:
```
2024-06-21 06:36:32.125 [ERR] CORE: notify: |ERROR| (send) Send error - Error encountered while sending btc: signing error: code 2: "internal error while executing RPC", raw tx: 01000000013bce0b69d6da04e40be0290b6d46547b72e315ef272b677ca623fcdacfbbc3d70000000000ffffffff0100e1f50500000000160014d9f7ed80387da2e0b57afc93b7fd2a06eecc3f9700000000
2024-06-21 06:36:32.125 [ERR] WEB: send/withdraw error: signing error: code 2: "internal error while executing RPC", raw tx: 01000000013bce0b69d6da04e40be0290b6d46547b72e315ef272b677ca623fcdacfbbc3d70000000000ffffffff0100e1f50500000000160014d9f7ed80387da2e0b57afc93b7fd2a06eecc3f9700000000
```

The electrum client says:
```
2665.74 | E | daemon.CommandsServer | internal error while executing RPC
Traceback (most recent call last):
  File "/home/joe/dextest/electrum/btc/client/electrum-repo/electrum/daemon.py", line 252, in handle
    response['result'] = await f(**params)
                         ^^^^^^^^^^^^^^^^^
  File "/home/joe/dextest/electrum/btc/client/electrum-repo/electrum/commands.py", line 163, in func_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joe/dextest/electrum/btc/client/electrum-repo/electrum/commands.py", line 476, in signtransaction
    wallet.sign_transaction(tx, password, ignore_warnings=iknowwhatimdoing)
  File "/home/joe/dextest/electrum/btc/client/electrum-repo/electrum/wallet.py", line 2543, in sign_transaction
    raise TransactionPotentiallyDangerousException('Not signing transaction:\n' + sh_danger.get_long_message())
electrum.wallet.TransactionPotentiallyDangerousException: Not signing transaction:
Warning: The fee could not be verified!
Warning: The input amounts could not be verified as the previous transactions are missing.
The amount of money being spent CANNOT be verified.
```

**Comment by JoeGruffins** [comment]
Looks like an extra check added here https://github.com/spesmilo/electrum/commit/7b96a83350c0d0c8f0b3e10710dc4314ff2190aa

**Comment by JoeGruffins** [comment]
Fixing.
