### ISSUE TITLE
MM bot spinning 

### ISSUE THREAD

**Issue by pubpete** [decred/dcrdex#2939]
I opened the Bison Wallet MM page and the previous MM I had is spinning and not giving me access to adjust it or start it.  

...After testing more, I had to delete my old MM settings for the DCR/USDT pair and then I was able to create again. 

![image](https://github.com/user-attachments/assets/bbd63158-5372-44b9-bcac-29df9c243890)

mm.ts:478 Uncaught (in promise) TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at c.<anonymous> (mm.ts:478:65)
    at p (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at o (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:22:9)

**Comment by buck54321** [comment]
This should have been fixed with #2920

**Comment by JoeGruffins** [comment]
likely fixed by the linked issue
