### ISSUE TITLE
eliminate time.Sleep from server/comms/comms_test.go

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#394]
We should plan to refactor the `comms` tests to eliminate sleeps by making use of the `wsConnStub.recv chan` that was added in https://github.com/decred/dcrdex/pull/287/commits/30fec9c817f7f9c575261a443f84a72233f177e2 for interested tests in to know when `(*wsConnStub).WriteMessage` did it's thing.

`time.Sleep` is quick but dirty unfortunately and CI apparently loves to preempt the test thread's CPU, breaking our assumptions about goroutine execution timing.

e.g.
https://github.com/decred/dcrdex/runs/694068914#step:5:92
have also seen `comms_test.go:427: error decoding last message (): unexpected end of JSON input`

**Comment by buck54321** [comment]
I'm on it.

**Comment by chappjc** [comment]
Add server/auth/auth_test.go to the list as well.  https://github.com/decred/dcrdex/pull/378/checks?check_run_id=694090213#step:5:174  :P  I blame go's unit test framework.  Anyway, might as well have a separate PR for that though.

**Comment by chappjc** [comment]
This one doesn't seem related to sleeps, but I'll drop it here since you're working on the comms test:

```
panic: test timed out after 10m0s

goroutine 13 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.14.3/x64/src/testing/testing.go:1459 +0x11c
created by time.goFunc
	/opt/hostedtoolcache/go/1.14.3/x64/src/time/sleep.go:168 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000132c60, 0xb07c88, 0x12, 0xb234f8, 0x1)
	/opt/hostedtoolcache/go/1.14.3/x64/src/testing/testing.go:1043 +0x699
testing.runTests.func1(0xc000132c60)
	/opt/hostedtoolcache/go/1.14.3/x64/src/testing/testing.go:1284 +0xa7
testing.tRunner(0xc000132c60, 0xc000163cb0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/testing/testing.go:991 +0x1ec
testing.runTests(0xc00000e4a0, 0xf47380, 0x6, 0x6, 0x0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/testing/testing.go:1282 +0x528
testing.(*M).Run(0xc000164180, 0x0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/testing/testing.go:1199 +0x300
decred.org/dcrdex/server/comms.TestMain(0xc000164180)
	/home/runner/work/dcrdex/dcrdex/server/comms/comms_test.go:209 +0x100
main.main()
	_testmain.go:52 +0x224

goroutine 9 [chan send]:
decred.org/dcrdex/server/comms.sendReplace(0xc000132fc0, 0xc000072280, 0xa99da0, 0xc000020e00, 0xb0341b, 0x9, 0xafe190, 0x1)
	/home/runner/work/dcrdex/dcrdex/server/comms/comms_test.go:177 +0x1f7
decred.org/dcrdex/server/comms.TestClientRequests.func12(0xb0341b, 0x9, 0xafe190, 0x1)
	/home/runner/work/dcrdex/dcrdex/server/comms/comms_test.go:343 +0x1ad
decred.org/dcrdex/server/comms.TestClientRequests(0xc000132fc0)
	/home/runner/work/dcrdex/dcrdex/server/comms/comms_test.go:358 +0x904
testing.tRunner(0xc000132fc0, 0xb234f8)
	/opt/hostedtoolcache/go/1.14.3/x64/src/testing/testing.go:991 +0x1ec
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.14.3/x64/src/testing/testing.go:1042 +0x661
FAIL	decred.org/dcrdex/server/comms	600.020s
```
