### ISSUE TITLE
server/swap: panic: nil pointer dereference in match.takerStatus.redemption.TxID()

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#490]
<details closed>
<summary>client</summary>

```
2020-06-16 16:19:40.000 [TRC] CORE: notify: |DATA| (epoch) - Index: 159229198
2020-06-16 16:19:40.003 [TRC] CORE: notify: |DATA| (epoch) - Index: 159229198
2020-06-16 16:19:40.013 [TRC] CORE: notify: |DATA| (epoch) - Index: 159229198
2020-06-16 16:19:40.017 [DBG] CORE: trade order 65c496e27020293498cadef24446850003edd437628b05108fbc8e0d82d4a70d matched with 1 orders
2020-06-16 16:19:40.017 [DBG] CORE: notify: |POKE| (order) Matches made - Sell order on dcr-btc 100.0% filled (65c496e2) - Order: 65c496e27020293498cadef24446850003edd437628b05108fbc8e0d82d4a70d
2020-06-16 16:19:40.027 [DBG] CORE[dcr]: 1 signature cycles to converge on fees for tx 000d8d063e6e8978c15d66acbd2a751708f282c27a3ef4e3a6f42ca597fba5f9
2020-06-16 16:19:40.036 [INF] CORE: Broadcasted 1 swap transactions for order 65c496e27020293498cadef24446850003edd437628b05108fbc8e0d82d4a70d. Contract coins: [000d8d063e6e8978c15d66acbd2a751708f282c27a3ef4e3a6f42ca597fba5f9:0]
2020-06-16 16:19:40.036 [DBG] CORE: notify: |POKE| (order) Swaps initiated - Sent swaps worth 1.00000000 dcr on order 65c496e2 - Order: 65c496e27020293498cadef24446850003edd437628b05108fbc8e0d82d4a70d
2020-06-16 16:19:40.038 [DBG] CORE: trade order 686dab7e4486c3049311833e08189f03de1b49b204b3c4bf2d86c748ee217c24 matched with 1 orders
2020-06-16 16:19:40.038 [DBG] CORE: notify: |POKE| (order) Matches made - Buy order on dcr-btc 100.0% filled (686dab7e) - Order: 686dab7e4486c3049311833e08189f03de1b49b204b3c4bf2d86c748ee217c24
2020-06-16 16:19:40.039 [INF] CORE: Audited contract (dcr: 000d8d063e6e8978c15d66acbd2a751708f282c27a3ef4e3a6f42ca597fba5f9:0) paying to SsjeJrcruFUrHNGdDxaFzYNi331m72fPL1T for order 686dab7e4486c3049311833e08189f03de1b49b204b3c4bf2d86c748ee217c24...
2020-06-16 16:19:43.928 [ERR] COMMS: read error (websocket: close 1006 (abnormal closure): unexpected EOF), attempting reconnection
2020-06-16 16:19:43.928 [INF] COMMS: Attempting to reconnect to wss://127.0.0.1:7232/ws...
2020-06-16 16:19:43.928 [ERR] COMMS: Reconnect failed: dial tcp 127.0.0.1:7232: connect: connection refused
2020-06-16 16:19:43.928 [INF] COMMS: Attempting reconnect to wss://127.0.0.1:7232/ws in 5 seconds.
2020-06-16 16:19:43.929 [WRN] CORE: notify: |WARNING| (conn) DEX disconnected - DEX at 127.0.0.1:7232 has disconnected
2020-06-16 16:19:48.928 [INF] COMMS: Attempting to reconnect to wss://127.0.0.1:7232/ws...
2020-06-16 16:19:48.928 [ERR] COMMS: Reconnect failed: dial tcp 127.0.0.1:7232: connect: connection refused
2020-06-16 16:19:48.929 [INF] COMMS: Attempting reconnect to wss://127.0.0.1:7232/ws in 10 seconds.
2020-06-16 16:19:53.912 [ERR] WEB: error placing order: timed out waiting for 'limit' response.
2020-06-16 16:19:53.965 [ERR] WEB: error placing order: cannot send on a broken connection
2020-06-16 16:19:58.929 [INF] COMMS: Attempting to reconnect to wss://127.0.0.1:7232/ws...
2020-06-16 16:19:58.929 [ERR] COMMS: Reconnect failed: dial tcp 127.0.0.1:7232: connect: connection refused
2020-06-16 16:19:58.929 [INF] COMMS: Attempting reconnect to wss://127.0.0.1:7232/ws in 15 seconds.
2020-06-16 16:20:00.881 [DBG] CORE: unsubscribing from dcr_ltc
2020-06-16 16:20:00.881 [ERR] CORE: request error unsubscribing from dcr_ltc orderbook: cannot send on a broken connection
2020-06-16 16:20:03.748 [DBG] CORE: unsubscribing from btc_ltc
2020-06-16 16:20:03.748 [ERR] CORE: request error unsubscribing from btc_ltc orderbook: cannot send on a broken connection
```
</details>

<details closed>
<summary>server</summary>

```
2020-06-16 16:19:40.000 [TRC] MKT: Preimage request sent for order 65c496e27020293498cadef24446850003edd437628b05108fbc8e0d82d4a70d
2020-06-16 16:19:40.000 [TRC] MKT: Preimage request sent for order 686dab7e4486c3049311833e08189f03de1b49b204b3c4bf2d86c748ee217c24
2020-06-16 16:19:40.000 [TRC] MKT: Good preimage received for order 65c496e27020293498cadef24446850003edd437628b05108fbc8e0d82d4a70d: e6238848a4fb6670426455e331226063520f847c21a32af90426c3fc12cb4e82
2020-06-16 16:19:40.004 [TRC] MKT: Good preimage received for order 686dab7e4486c3049311833e08189f03de1b49b204b3c4bf2d86c748ee217c24: 0b71dce31a3bb083dfe7283a4e9b3217e521f107a6c5bac96bdf45e09c845ba3
2020-06-16 16:19:40.005 [INF] MKT: Collected 2 valid order preimages, missed 0. Commit checksum: 221986f5731d1d25d2ffce40a0833a5280ecce15c59019adae5c564134f5d608
2020-06-16 16:19:40.006 [INF] MKT: Matching complete for market dcr_btc epoch 159229197: 1 matches (0 partial fills), 1 completed OK (not booked), 1 booked, 1 unbooked, 0 failed
2020-06-16 16:19:40.012 [DBG] MKT: Negotiating 1 matches for epoch 159229197:10000
2020-06-16 16:19:40.014 [DBG] SWAP: Negotiate: sending 'match' ack request to user d2881e5d2b49368d531d44f3d55406334a6bd4f2bf9926796dd0c039bde4dfad for 2 matches
2020-06-16 16:19:40.015 [DBG] SWAP: processMatchAcks: 'match' ack received from d2881e5d2b49368d531d44f3d55406334a6bd4f2bf9926796dd0c039bde4dfad for 2 matches
2020-06-16 16:19:40.017 [DBG] SWAP: processMatchAcks: storing valid 'match' ack signature from d2881e5d2b49368d531d44f3d55406334a6bd4f2bf9926796dd0c039bde4dfad (maker=true) for match eabf52cb5f6d8846abdf09b8c4b8fd61b9cd4715e3c4c222bcaa0deaefe78e8e (status NewlyMatched)
2020-06-16 16:19:40.019 [DBG] SWAP: processMatchAcks: storing valid 'match' ack signature from d2881e5d2b49368d531d44f3d55406334a6bd4f2bf9926796dd0c039bde4dfad (maker=false) for match eabf52cb5f6d8846abdf09b8c4b8fd61b9cd4715e3c4c222bcaa0deaefe78e8e (status NewlyMatched)
2020-06-16 16:19:40.031 [DBG] SWAP: handleInit: 'init' received from d2881e5d2b49368d531d44f3d55406334a6bd4f2bf9926796dd0c039bde4dfad for match eabf52cb5f6d8846abdf09b8c4b8fd61b9cd4715e3c4c222bcaa0deaefe78e8e, order 65c496e27020293498cadef24446850003edd437628b05108fbc8e0d82d4a70d
2020-06-16 16:19:40.031 [DBG] SWAP: step(user=d2881e5d2b49368d531d44f3d55406334a6bd4f2bf9926796dd0c039bde4dfad, match=eabf52cb5f6d8846abdf09b8c4b8fd61b9cd4715e3c4c222bcaa0deaefe78e8e): ready for user d2881e5d2b49368d531d44f3d55406334a6bd4f2bf9926796dd0c039bde4dfad action, status NewlyMatched, next MakerSwapCast
2020-06-16 16:19:40.034 [DBG] SWAP: processInit: valid contract received at 2020-06-16 07:19:40.033 +0000 UTC from d2881e5d2b49368d531d44f3d55406334a6bd4f2bf9926796dd0c039bde4dfad for match eabf52cb5f6d8846abdf09b8c4b8fd61b9cd4715e3c4c222bcaa0deaefe78e8e, swapStatus NewlyMatched => MakerSwapCast
2020-06-16 16:19:40.034 [DBG] SWAP: processInit: sending contract 'audit' ack request to counterparty d2881e5d2b49368d531d44f3d55406334a6bd4f2bf9926796dd0c039bde4dfad for match eabf52cb5f6d8846abdf09b8c4b8fd61b9cd4715e3c4c222bcaa0deaefe78e8e
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x990a32]

goroutine 4147 [running]:
decred.org/dcrdex/server/swap.(*Swapper).TxMonitored.func1(0xc00050ed80, 0xc0001fd200)
        /home/joe/git/dcrdex/server/swap/swap.go:1052 +0x5b2
decred.org/dcrdex/server/swap.(*Swapper).TxMonitored(0xc000324160, 0x8d36492b5d1e88d2, 0x330654d5f3441d53, 0x792699bff2d46b4a, 0xaddfe4bd39c0d06d, 0xa6f42ca50000002a, 0xc0049d0e00, 0x40, 0xd8d063e6e8900)
        /home/joe/git/dcrdex/server/swap/swap.go:1078 +0x164
decred.org/dcrdex/server/market.(*Market).TxMonitored(0xc000648000, 0x8d36492b5d1e88d2, 0x330654d5f3441d53, 0x792699bff2d46b4a, 0xaddfe4bd39c0d06d, 0x2a, 0xc0049d0e00, 0x40, 0xc004d165e8)
        /home/joe/git/dcrdex/server/market/market.go:445 +0x73
decred.org/dcrdex/server/market.(*OrderRouter).checkPrefixTrade(0xc0000a6640, 0x8d36492b5d1e88d2, 0x330654d5f3441d53, 0x792699bff2d46b4a, 0xaddfe4bd39c0d06d, 0xe52f40, 0xc000648000, 0xc0049c6c40, 0xc0049b56b0, 0xc0049b5718, ...)
        /home/joe/git/dcrdex/server/market/orderrouter.go:661 +0xa65
decred.org/dcrdex/server/market.(*OrderRouter).handleLimit(0xc0000a6640, 0x8d36492b5d1e88d2, 0x330654d5f3441d53, 0x792699bff2d46b4a, 0xaddfe4bd39c0d06d, 0xc04a36b8c0, 0xd74828)
        /home/joe/git/dcrdex/server/market/orderrouter.go:198 +0x23e
decred.org/dcrdex/server/auth.(*AuthManager).Route.func1(0xe51ec0, 0xc0001fc3f0, 0xc04a36b8c0, 0x5)
        /home/joe/git/dcrdex/server/auth/auth.go:274 +0x173
decred.org/dcrdex/server/comms.handleMessage(0xc0001fc3f0, 0xc04a36b8c0, 0xc0049b5600)
        /home/joe/git/dcrdex/server/comms/link.go:99 +0x9c
decred.org/dcrdex/server/comms.newWSLink.func1(0xc04a36b8c0, 0x36a)
        /home/joe/git/dcrdex/server/comms/link.go:62 +0x37
decred.org/dcrdex/dex/ws.(*WSLink).inHandler(0xc049fe5620, 0xe4d260, 0xc049fc3cc0)
        /home/joe/git/dcrdex/dex/ws/wslink.go:236 +0x1d8
created by decred.org/dcrdex/dex/ws.(*WSLink).Connect
        /home/joe/git/dcrdex/dex/ws/wslink.go:169 +0x30f
[joe@hyrule dcrdex]$
```
</details>

**Comment by chappjc** [comment]
Closed by https://github.com/decred/dcrdex/pull/499
