### ISSUE TITLE
reconfigure wallet panic

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdex#751]
While testing PR https://github.com/decred/dcrdex/pull/741, I got the following panic when attempting to reconfigure the DCR wallet via browser ui:

```
2020-10-15 22:41:32.278 [INF] CORE[dcr]: Setting up new DCR wallet at 127.0.0.1:19568 with TLS certificate "/home/jon/dextest/dcr/beta/rpc.cert".
2020-10-15 22:41:32.364 [INF] CORE[dcr]: Connected to dcrwallet (JSON-RPC API v8.4.0) proxying dcrd (JSON-RPC API v6.1.2) on SimNet
Panic: runtime error: invalid memory address or nil pointer dereference
goroutine 19005 [running]:
runtime/debug.Stack(0xf7826b, 0x48, 0x50)
	/home/jon/go115/src/runtime/debug/stack.go:24 +0xab
runtime/debug.PrintStack()
	/home/jon/go115/src/runtime/debug/stack.go:16 +0x34
github.com/go-chi/chi/middleware.Recoverer.func1.1(0xc000fa2600, 0x1424f40, 0xc000f102a0)
	/home/jon/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/middleware/recoverer.go:28 +0x20b
panic(0x10b6ea0, 0x18d1ba0)
	/home/jon/go115/src/runtime/panic.go:975 +0x47a
sync.(*WaitGroup).state(...)
	/home/jon/go115/src/sync/waitgroup.go:33
sync.(*WaitGroup).Wait(0x0)
	/home/jon/go115/src/sync/waitgroup.go:104 +0x34
decred.org/dcrdex/dex.(*ConnectionMaster).Disconnect(0xc0000963c0)
	/home/jon/github/decred/dcrdex/dex/runner.go:114 +0xb7
decred.org/dcrdex/client/core.(*xcWallet).Disconnect(0xc0006b81e0)
	/home/jon/github/decred/dcrdex/client/core/wallet.go:125 +0x57
decred.org/dcrdex/client/core.(*Core).ReconfigureWallet(0xc00059c280, 0xc0009a9b1d, 0x1, 0x1, 0xc00000002a, 0xc000f9ce70, 0x0, 0x0)
	/home/jon/github/decred/dcrdex/client/core/core.go:1431 +0xfc5
decred.org/dcrdex/client/webserver.(*WebServer).apiReconfig(0xc00015e2a0, 0x1424f40, 0xc000f102a0, 0xc000fa2700)
	/home/jon/github/decred/dcrdex/client/webserver/api.go:408 +0x242
net/http.HandlerFunc.ServeHTTP(0xc0001f8ab0, 0x1424f40, 0xc000f102a0, 0xc000fa2700)
	/home/jon/go115/src/net/http/server.go:2042 +0x52
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0001f7200, 0x1424f40, 0xc000f102a0, 0xc000fa2700)
	/home/jon/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:425 +0x3f8
net/http.HandlerFunc.ServeHTTP(0xc0001f8990, 0x1424f40, 0xc000f102a0, 0xc000fa2700)
	/home/jon/go115/src/net/http/server.go:2042 +0x52
github.com/go-chi/chi/middleware.AllowContentType.func1.1(0x1424f40, 0xc000f102a0, 0xc000fa2700)
	/home/jon/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/middleware/content_type.go:42 +0x242
net/http.HandlerFunc.ServeHTTP(0xc000868a50, 0x1424f40, 0xc000f102a0, 0xc000fa2700)
	/home/jon/go115/src/net/http/server.go:2042 +0x52
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0001f7200, 0x1424f40, 0xc000f102a0, 0xc000fa2700)
	/home/jon/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:70 +0xa3c
github.com/go-chi/chi.(*Mux).Mount.func1(0x1424f40, 0xc000f102a0, 0xc000fa2700)
	/home/jon/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:292 +0x1fb
net/http.HandlerFunc.ServeHTTP(0xc000519260, 0x1424f40, 0xc000f102a0, 0xc000fa2700)
	/home/jon/go115/src/net/http/server.go:2042 +0x52
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0001f6fc0, 0x1424f40, 0xc000f102a0, 0xc000fa2700)
	/home/jon/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:425 +0x3f8
net/http.HandlerFunc.ServeHTTP(0xc0001f87a0, 0x1424f40, 0xc000f102a0, 0xc000fa2700)
	/home/jon/go115/src/net/http/server.go:2042 +0x52
decred.org/dcrdex/client/webserver.(*WebServer).authMiddleware.func1(0x1424f40, 0xc000f102a0, 0xc000fa2600)
	/home/jon/github/decred/dcrdex/client/webserver/middleware.go:58 +0x4f5
net/http.HandlerFunc.ServeHTTP(0xc000518ae0, 0x1424f40, 0xc000f102a0, 0xc000fa2600)
	/home/jon/go115/src/net/http/server.go:2042 +0x52
github.com/go-chi/chi/middleware.Recoverer.func1(0x1424f40, 0xc000f102a0, 0xc000fa2600)
	/home/jon/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/middleware/recoverer.go:35 +0xf3
net/http.HandlerFunc.ServeHTTP(0xc000518b00, 0x1424f40, 0xc000f102a0, 0xc000fa2600)
	/home/jon/go115/src/net/http/server.go:2042 +0x52
decred.org/dcrdex/client/webserver.securityMiddleware.func1(0x1424f40, 0xc000f102a0, 0xc000fa2600)
	/home/jon/github/decred/dcrdex/client/webserver/middleware.go:32 +0x6fb
net/http.HandlerFunc.ServeHTTP(0xc000518b20, 0x1424f40, 0xc000f102a0, 0xc000fa2600)
	/home/jon/go115/src/net/http/server.go:2042 +0x52
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0001f6fc0, 0x1424f40, 0xc000f102a0, 0xc000fa2500)
	/home/jon/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:82 +0x675
net/http.serverHandler.ServeHTTP(0xc0005a81c0, 0x1424f40, 0xc000f102a0, 0xc000fa2500)
	/home/jon/go115/src/net/http/server.go:2843 +0xcb
net/http.(*conn).serve(0xc000d4a320, 0x1427380, 0xc000ec3740)
	/home/jon/go115/src/net/http/server.go:1925 +0x84d
created by net/http.(*Server).Serve
	/home/jon/go115/src/net/http/server.go:2969 +0x5d4
```

This was after running a ton of swaps on the DCR_BTC market, and the dcrwallet was still unlocked and connected.

**Comment by chappjc** [comment]
I can reproduce this by changing the BTC wallet settings, then trying to change DCR wallet settings
